/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskItemDto } from '../../models/task-item-dto';

export interface TaskGet$Params {
  id: number;
}

export function taskGet(http: HttpClient, rootUrl: string, params: TaskGet$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskItemDto>> {
  const rb = new RequestBuilder(rootUrl, taskGet.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskItemDto>;
    })
  );
}

taskGet.PATH = '/api/tasks/{id}';
