/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskItemDto } from '../../models/task-item-dto';

export interface TaskList$Params {
  backlogId: number;
}

export function taskList(http: HttpClient, rootUrl: string, params: TaskList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TaskItemDto>>> {
  const rb = new RequestBuilder(rootUrl, taskList.PATH, 'get');
  if (params) {
    rb.query('backlogId', params.backlogId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TaskItemDto>>;
    })
  );
}

taskList.PATH = '/api/tasks';
