/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TaskCreateRequest } from '../../models/task-create-request';
import { TaskItemDto } from '../../models/task-item-dto';

export interface TaskCreate$Params {
      body: TaskCreateRequest
}

export function taskCreate(http: HttpClient, rootUrl: string, params: TaskCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskItemDto>> {
  const rb = new RequestBuilder(rootUrl, taskCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskItemDto>;
    })
  );
}

taskCreate.PATH = '/api/tasks';
