/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MissingLogWarning } from '../../models/missing-log-warning';

export interface ReportsMissingLogs$Params {
}

export function reportsMissingLogs(http: HttpClient, rootUrl: string, params?: ReportsMissingLogs$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<MissingLogWarning>>> {
  const rb = new RequestBuilder(rootUrl, reportsMissingLogs.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<MissingLogWarning>>;
    })
  );
}

reportsMissingLogs.PATH = '/api/reports/missing-logs';
