/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimesheetWeeklyReportResponse } from '../../models/timesheet-weekly-report-response';

export interface ReportsWeekly$Params {
  monday: string;
  userId?: number;
  project?: string;
  teamIds?: Array<number>;
}

export function reportsWeekly(http: HttpClient, rootUrl: string, params: ReportsWeekly$Params, context?: HttpContext): Observable<StrictHttpResponse<TimesheetWeeklyReportResponse>> {
  const rb = new RequestBuilder(rootUrl, reportsWeekly.PATH, 'get');
  if (params) {
    rb.query('monday', params.monday, {});
    rb.query('userId', params.userId, {});
    rb.query('project', params.project, {});
    rb.query('teamIds', params.teamIds, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimesheetWeeklyReportResponse>;
    })
  );
}

reportsWeekly.PATH = '/api/reports/weekly';
