/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TimesheetMonthlyReportResponse } from '../../models/timesheet-monthly-report-response';

export interface ReportsMonthly$Params {
  year: number;
  month: number;
  userId?: number;
  project?: string;
}

export function reportsMonthly(http: HttpClient, rootUrl: string, params: ReportsMonthly$Params, context?: HttpContext): Observable<StrictHttpResponse<TimesheetMonthlyReportResponse>> {
  const rb = new RequestBuilder(rootUrl, reportsMonthly.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('month', params.month, {});
    rb.query('userId', params.userId, {});
    rb.query('project', params.project, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TimesheetMonthlyReportResponse>;
    })
  );
}

reportsMonthly.PATH = '/api/reports/monthly';
