/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DefaultTaskDto } from '../../models/default-task-dto';

export interface DefaultTaskListAll$Params {
}

export function defaultTaskListAll(http: HttpClient, rootUrl: string, params?: DefaultTaskListAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DefaultTaskDto>>> {
  const rb = new RequestBuilder(rootUrl, defaultTaskListAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<DefaultTaskDto>>;
    })
  );
}

defaultTaskListAll.PATH = '/api/default-tasks/all';
