/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsTemplateCreateRequest } from '../../models/settings-template-create-request';
import { TaskTemplateDto } from '../../models/task-template-dto';

export interface TemplateCreate$Params {
      body: SettingsTemplateCreateRequest
}

export function templateCreate(http: HttpClient, rootUrl: string, params: TemplateCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TaskTemplateDto>> {
  const rb = new RequestBuilder(rootUrl, templateCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TaskTemplateDto>;
    })
  );
}

templateCreate.PATH = '/api/templates';
