/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RetentionPreview } from '../../models/retention-preview';

export interface OpsRetentionPreview$Params {
}

export function opsRetentionPreview(http: HttpClient, rootUrl: string, params?: OpsRetentionPreview$Params, context?: HttpContext): Observable<StrictHttpResponse<RetentionPreview>> {
  const rb = new RequestBuilder(rootUrl, opsRetentionPreview.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RetentionPreview>;
    })
  );
}

opsRetentionPreview.PATH = '/api/ops/retention/preview';
