/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsOpsResult } from '../../models/settings-ops-result';

export interface OpsExportRun$Params {
}

export function opsExportRun(http: HttpClient, rootUrl: string, params?: OpsExportRun$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsOpsResult>> {
  const rb = new RequestBuilder(rootUrl, opsExportRun.PATH, 'post');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsOpsResult>;
    })
  );
}

opsExportRun.PATH = '/api/ops/export/run';
