/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsOpsBackupSettings } from '../../models/settings-ops-backup-settings';

export interface OpsBackupSettingsSet$Params {
      body: SettingsOpsBackupSettings
}

export function opsBackupSettingsSet(http: HttpClient, rootUrl: string, params: OpsBackupSettingsSet$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsOpsBackupSettings>> {
  const rb = new RequestBuilder(rootUrl, opsBackupSettingsSet.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsOpsBackupSettings>;
    })
  );
}

opsBackupSettingsSet.PATH = '/api/ops/backup/settings';
