/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsNameRequest } from '../../models/settings-name-request';
import { TeamDto } from '../../models/team-dto';

export interface TeamCreate$Params {
      body: SettingsNameRequest
}

export function teamCreate(http: HttpClient, rootUrl: string, params: TeamCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<TeamDto>> {
  const rb = new RequestBuilder(rootUrl, teamCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TeamDto>;
    })
  );
}

teamCreate.PATH = '/api/teams';
