/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NamedRefDto } from '../../models/named-ref-dto';

export interface UserNames$Params {
}

export function userNames(http: HttpClient, rootUrl: string, params?: UserNames$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<NamedRefDto>>> {
  const rb = new RequestBuilder(rootUrl, userNames.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<NamedRefDto>>;
    })
  );
}

userNames.PATH = '/api/users/names';
