/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface TaskListExport$Params {
  year: number;
  month: number;
  teamIds?: Array<number>;
}

export function taskListExport(http: HttpClient, rootUrl: string, params: TaskListExport$Params, context?: HttpContext): Observable<StrictHttpResponse<string>> {
  const rb = new RequestBuilder(rootUrl, taskListExport.PATH, 'get');
  if (params) {
    rb.query('year', params.year, {});
    rb.query('month', params.month, {});
    rb.query('teamIds', params.teamIds, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: 'text/markdown', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<string>;
    })
  );
}

taskListExport.PATH = '/api/tasklist/export';
