/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TaskNode } from '../models/task-node';
export interface BacklogNode {
  backlogCode?: string | null;
  project?: string | null;
  tasks?: Array<TaskNode> | null;
  totalHours?: number;
}
