/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BacklogListItemDto {
  assigneeUserId?: number | null;
  backlogCode?: string | null;
  id?: number;
  periodMonth?: string | null;
  project?: string | null;
  taskCount?: number;
  teamId?: number | null;
  type?: string | null;
}
