/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BacklogAuditDto {
  changedAt?: string;
  changedByName?: string | null;
  field?: string | null;
  id?: number;
  newValue?: string | null;
  note?: string | null;
  oldValue?: string | null;
}
