/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ConflictBody {
  deleted?: boolean;
  detail?: string | null;
  id?: number;
  message?: string | null;
  table?: string | null;
}
