/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduleState } from '../models/schedule-state';
export interface GanttBar {
  backlogCode?: string | null;
  backlogId?: number;
  end?: string | null;
  externalMarkerIndex?: number | null;
  hasStart?: boolean;
  scheduleState?: ScheduleState;
  spanWorkingDays?: number;
  start?: string | null;
  startDayIndex?: number;
}
