/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GanttBar } from '../models/gantt-bar';
export interface GanttModel {
  axis?: Array<string> | null;
  bars?: Array<GanttBar> | null;
}
