/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MeResponse {
  activeTeamId?: number;
  id?: number;
  isAdmin?: boolean;
  memberTeamIds?: Array<number> | null;
  name?: string | null;
}
