/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MonthlyBacklogTaskTotal {
  backlogCode?: string | null;
  project?: string | null;
  taskName?: string | null;
  totalHours?: number;
}
