/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BacklogNode } from '../models/backlog-node';
export interface ProjectNode {
  backlogs?: Array<BacklogNode> | null;
  project?: string | null;
  totalHours?: number;
}
