/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RetentionMonthPreview } from '../models/retention-month-preview';
export interface RetentionPreview {
  cutoff?: string | null;
  months?: Array<RetentionMonthPreview> | null;
}
