/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RetentionMonthPreview {
  backlogs?: number;
  month?: string | null;
  standupEntries?: number;
  standupIssues?: number;
  tasks?: number;
  timeLogs?: number;
}
