/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduleState } from './schedule-state';

/**
 * Each possible value of `ScheduleState`
 */
export const SCHEDULE_STATE: ScheduleState[] = [
  0,
  1,
  2
];