/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsStandupEntryUpdateRequest {
  backlogCode?: string | null;
  backlogId?: number | null;
  deadline?: string | null;
  description?: string | null;
  section?: string | null;
  status?: string | null;
  taskText?: string | null;
}
