/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SettingsStandupEntryView } from '../models/settings-standup-entry-view';
export interface SettingsUserStandup {
  today?: Array<SettingsStandupEntryView> | null;
  userId?: number;
  userName?: string | null;
  yesterday?: Array<SettingsStandupEntryView> | null;
}
