/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsOpsBackupSettings {
  autoBackupEnabled?: boolean;
  backupFolderPath?: string | null;
  backupKeepCount?: number;
}
