/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsTemplateCreateRequest {
  orderIndex?: number;
  taskName?: string | null;
  templateName?: string | null;
}
