/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { StandupEntryDto } from '../models/standup-entry-dto';
import { StandupIssueDto } from '../models/standup-issue-dto';
export interface SettingsStandupEntryView {
  editable?: boolean;
  entry?: StandupEntryDto;
  issues?: Array<StandupIssueDto> | null;
}
