/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsStandupIssueCreateRequest {
  issueText?: string | null;
  solutionText?: string | null;
  status?: string | null;
}
