/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsTagUpdateRequest {
  color?: string | null;
  expectedVersion?: number;
  icon?: string | null;
  text?: string | null;
}
