/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BackupInfo } from '../models/backup-info';
export interface SettingsOpsBackupList {
  backups?: Array<BackupInfo> | null;
  folderConfigured?: boolean;
}
