/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SettingsStandupIssueUpdateRequest {
  expectedVersion?: number;
  issueText?: string | null;
  solutionText?: string | null;
  status?: string | null;
}
