/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SmartFillTaskRequest } from '../models/smart-fill-task-request';
export interface SmartFillRequest {
  tasks?: Array<SmartFillTaskRequest> | null;
}
