/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SmartFillCellRequest } from '../models/smart-fill-cell-request';
export interface SmartFillTaskRequest {
  cells?: Array<SmartFillCellRequest> | null;
  taskId?: number;
}
