/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StandupIssueDto {
  entryId?: number;
  id?: number;
  issueText?: string | null;
  orderIndex?: number;
  rowVersion?: number;
  solutionText?: string | null;
  status?: string | null;
}
