/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StandupEntryDto {
  backlogCode?: string | null;
  backlogId?: number | null;
  deadline?: string | null;
  description?: string | null;
  id?: number;
  orderIndex?: number;
  section?: string | null;
  status?: string | null;
  taskText?: string | null;
  teamId?: number | null;
  userId?: number;
  workDate?: string;
}
