/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TagDto {
  color?: string | null;
  icon?: string | null;
  id?: number;
  rowVersion?: number;
  text?: string | null;
}
