/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ScheduleState } from '../models/schedule-state';
import { TagDto } from '../models/tag-dto';
import { TaskItemDto } from '../models/task-item-dto';
export interface TaskListRowDto {
  assigneeUserId?: number | null;
  backlogCode?: string | null;
  backlogId?: number;
  deadlineExternal?: string | null;
  deadlineInternal?: string | null;
  endDate?: string | null;
  estimateHours?: number | null;
  loggedHours?: number;
  pcaContactId?: number | null;
  pcaContactName?: string | null;
  pctAssigneeName?: string | null;
  progressPercent?: number | null;
  project?: string | null;
  scheduleState?: ScheduleState;
  startDate?: string | null;
  tags?: Array<TagDto> | null;
  tasks?: Array<TaskItemDto> | null;
  teamId?: number | null;
  type?: string | null;
}
