/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DateEntry } from '../models/date-entry';
export interface TaskNode {
  dates?: Array<DateEntry> | null;
  taskId?: number;
  taskName?: string | null;
  totalHours?: number;
}
