/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GanttModel } from '../models/gantt-model';
import { TaskListRowDto } from '../models/task-list-row-dto';
export interface TaskListScreenDto {
  gantt?: GanttModel;
  rows?: Array<TaskListRowDto> | null;
}
