/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskTemplateDto {
  id?: number;
  orderIndex?: number;
  taskName?: string | null;
  templateName?: string | null;
}
