/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskUpdateRequest {
  expectedVersion?: number;
  orderIndex?: number;
  status?: string | null;
  taskName?: string | null;
}
