/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TaskExtendedRequest {
  assigneeUserId?: number | null;
  expectedVersion?: number;
  type?: string | null;
}
