/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ProjectNode } from '../models/project-node';
export interface TeamNode {
  projects?: Array<ProjectNode> | null;
  teamName?: string | null;
  totalHours?: number;
}
