/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TeamDto {
  createdAt?: string;
  id?: number;
  isActive?: boolean;
  name?: string | null;
  rowVersion?: number;
}
