/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimesheetSaveCellRequest {
  date?: string;
  expectedVersion?: number | null;
  hours?: number;
  taskId?: number;
}
