/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TimeLogDto {
  hours?: number;
  id?: number;
  rowVersion?: number;
  taskId?: number;
  userId?: number;
  workDate?: string;
}
