/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  id?: number;
  isActive?: boolean;
  isAdmin?: boolean;
  name?: string | null;
  rowVersion?: number;
  username?: string | null;
}
