/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface WeeklyDetailRow {
  backlogCode?: string | null;
  date?: string;
  project?: string | null;
  taskName?: string | null;
  totalHours?: number;
}
