/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { WeekCell } from '../models/week-cell';
export interface WeekRow {
  backlogCode?: string | null;
  fri?: WeekCell;
  mon?: WeekCell;
  orderIndex?: number;
  taskId?: number;
  taskName?: string | null;
  thu?: WeekCell;
  tue?: WeekCell;
  wed?: WeekCell;
}
