/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SavedBody } from '../../models/saved-body';
import { TimesheetSaveCellRequest } from '../../models/timesheet-save-cell-request';

export interface TimesheetSaveCell$Params {
      body: TimesheetSaveCellRequest
}

export function timesheetSaveCell(http: HttpClient, rootUrl: string, params: TimesheetSaveCell$Params, context?: HttpContext): Observable<StrictHttpResponse<SavedBody>> {
  const rb = new RequestBuilder(rootUrl, timesheetSaveCell.PATH, 'put');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SavedBody>;
    })
  );
}

timesheetSaveCell.PATH = '/api/timesheet/cell';
