/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WeekBacklogGroup } from '../../models/week-backlog-group';

export interface TimesheetWeek$Params {
  monday: string;
  allUsers?: boolean;
}

export function timesheetWeek(http: HttpClient, rootUrl: string, params: TimesheetWeek$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<WeekBacklogGroup>>> {
  const rb = new RequestBuilder(rootUrl, timesheetWeek.PATH, 'get');
  if (params) {
    rb.query('monday', params.monday, {});
    rb.query('allUsers', params.allUsers, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<WeekBacklogGroup>>;
    })
  );
}

timesheetWeek.PATH = '/api/timesheet/week';
