/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsUserStandup } from '../../models/settings-user-standup';

export interface StandupMyDay$Params {
  date?: string;
}

export function standupMyDay(http: HttpClient, rootUrl: string, params?: StandupMyDay$Params, context?: HttpContext): Observable<StrictHttpResponse<SettingsUserStandup>> {
  const rb = new RequestBuilder(rootUrl, standupMyDay.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SettingsUserStandup>;
    })
  );
}

standupMyDay.PATH = '/api/standup/entries';
