/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SavedBody } from '../../models/saved-body';
import { SettingsStandupIssueUpdateRequest } from '../../models/settings-standup-issue-update-request';

export interface StandupIssueUpdate$Params {
  entryId: number;
  issueId: number;
      body: SettingsStandupIssueUpdateRequest
}

export function standupIssueUpdate(http: HttpClient, rootUrl: string, params: StandupIssueUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<SavedBody>> {
  const rb = new RequestBuilder(rootUrl, standupIssueUpdate.PATH, 'put');
  if (params) {
    rb.path('entryId', params.entryId, {});
    rb.path('issueId', params.issueId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SavedBody>;
    })
  );
}

standupIssueUpdate.PATH = '/api/standup/entries/{entryId}/issues/{issueId}';
