/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchivedFileDto } from '../../models/archived-file-dto';

export interface StandupArchiveWeek$Params {
  date: string;
}

export function standupArchiveWeek(http: HttpClient, rootUrl: string, params: StandupArchiveWeek$Params, context?: HttpContext): Observable<StrictHttpResponse<ArchivedFileDto>> {
  const rb = new RequestBuilder(rootUrl, standupArchiveWeek.PATH, 'post');
  if (params) {
    rb.query('date', params.date, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ArchivedFileDto>;
    })
  );
}

standupArchiveWeek.PATH = '/api/standup/archive';
