/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsUserStandup } from '../../models/settings-user-standup';

export interface StandupBoard$Params {
  date?: string;
  teamIds?: Array<number>;
}

export function standupBoard(http: HttpClient, rootUrl: string, params?: StandupBoard$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SettingsUserStandup>>> {
  const rb = new RequestBuilder(rootUrl, standupBoard.PATH, 'get');
  if (params) {
    rb.query('date', params.date, {});
    rb.query('teamIds', params.teamIds, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<SettingsUserStandup>>;
    })
  );
}

standupBoard.PATH = '/api/standup/board';
