/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface StandupIssueDelete$Params {
  entryId: number;
  issueId: number;
}

export function standupIssueDelete(http: HttpClient, rootUrl: string, params: StandupIssueDelete$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, standupIssueDelete.PATH, 'delete');
  if (params) {
    rb.path('entryId', params.entryId, {});
    rb.path('issueId', params.issueId, {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

standupIssueDelete.PATH = '/api/standup/entries/{entryId}/issues/{issueId}';
