/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SettingsStandupIssueCreateRequest } from '../../models/settings-standup-issue-create-request';

export interface StandupIssueCreate$Params {
  entryId: number;
      body: SettingsStandupIssueCreateRequest
}

export function standupIssueCreate(http: HttpClient, rootUrl: string, params: StandupIssueCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<number>> {
  const rb = new RequestBuilder(rootUrl, standupIssueCreate.PATH, 'post');
  if (params) {
    rb.path('entryId', params.entryId, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: parseFloat(String((r as HttpResponse<any>).body)) }) as StrictHttpResponse<number>;
    })
  );
}

standupIssueCreate.PATH = '/api/standup/entries/{entryId}/issues';
