/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SmartFillRequest } from '../../models/smart-fill-request';
import { TimeLogDto } from '../../models/time-log-dto';

export interface SmartFillApply$Params {
      body: SmartFillRequest
}

export function smartFillApply(http: HttpClient, rootUrl: string, params: SmartFillApply$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<TimeLogDto>>> {
  const rb = new RequestBuilder(rootUrl, smartFillApply.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<TimeLogDto>>;
    })
  );
}

smartFillApply.PATH = '/api/smartfill/apply';
