/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogCreateRequest } from '../../models/backlog-create-request';
import { BacklogDto } from '../../models/backlog-dto';

export interface BacklogCreate$Params {
      body: BacklogCreateRequest
}

export function backlogCreate(http: HttpClient, rootUrl: string, params: BacklogCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogDto>> {
  const rb = new RequestBuilder(rootUrl, backlogCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BacklogDto>;
    })
  );
}

backlogCreate.PATH = '/api/backlogs';
