/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogContinueRequest } from '../../models/backlog-continue-request';
import { BacklogDto } from '../../models/backlog-dto';

export interface BacklogContinue$Params {
  id: number;
      body: BacklogContinueRequest
}

export function backlogContinue(http: HttpClient, rootUrl: string, params: BacklogContinue$Params, context?: HttpContext): Observable<StrictHttpResponse<BacklogDto>> {
  const rb = new RequestBuilder(rootUrl, backlogContinue.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BacklogDto>;
    })
  );
}

backlogContinue.PATH = '/api/backlogs/{id}/continue';
