/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogTagsRequest } from '../../models/backlog-tags-request';
import { SavedBody } from '../../models/saved-body';

export interface BacklogSetTags$Params {
  id: number;
      body: BacklogTagsRequest
}

export function backlogSetTags(http: HttpClient, rootUrl: string, params: BacklogSetTags$Params, context?: HttpContext): Observable<StrictHttpResponse<SavedBody>> {
  const rb = new RequestBuilder(rootUrl, backlogSetTags.PATH, 'put');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SavedBody>;
    })
  );
}

backlogSetTags.PATH = '/api/backlogs/{id}/tags';
