/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BacklogListItemDto } from '../../models/backlog-list-item-dto';

export interface BacklogList$Params {
  term?: string;
}

export function backlogList(http: HttpClient, rootUrl: string, params?: BacklogList$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<BacklogListItemDto>>> {
  const rb = new RequestBuilder(rootUrl, backlogList.PATH, 'get');
  if (params) {
    rb.query('term', params.term, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<BacklogListItemDto>>;
    })
  );
}

backlogList.PATH = '/api/backlogs';
