/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PcaContactDto } from '../../models/pca-contact-dto';
import { SettingsNameRequest } from '../../models/settings-name-request';

export interface PcaContactCreate$Params {
      body: SettingsNameRequest
}

export function pcaContactCreate(http: HttpClient, rootUrl: string, params: PcaContactCreate$Params, context?: HttpContext): Observable<StrictHttpResponse<PcaContactDto>> {
  const rb = new RequestBuilder(rootUrl, pcaContactCreate.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PcaContactDto>;
    })
  );
}

pcaContactCreate.PATH = '/api/pca-contacts';
