/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PcaContactDto } from '../../models/pca-contact-dto';

export interface PcaContactListAll$Params {
}

export function pcaContactListAll(http: HttpClient, rootUrl: string, params?: PcaContactListAll$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<PcaContactDto>>> {
  const rb = new RequestBuilder(rootUrl, pcaContactListAll.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<PcaContactDto>>;
    })
  );
}

pcaContactListAll.PATH = '/api/pca-contacts/all';
